// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: message.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace SkillBridge.Message
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NUserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"player")]
        public NPlayerInfo Player { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NPlayerInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"characters")]
        public global::System.Collections.Generic.List<NCharacterInfo> Characters { get; } = new global::System.Collections.Generic.List<NCharacterInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NCharacterInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tid")]
        public int Tid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"type")]
        public CharacterType Type { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"class")]
        public CharacterClass Class { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"level")]
        public int Level { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int mapId { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"entity")]
        public NEntity Entity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NVector3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x")]
        public int X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y")]
        public int Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z")]
        public int Z { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NEntity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"position")]
        public NVector3 Position { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"direction")]
        public NVector3 Direction { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"speed")]
        public int Speed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NEntitySync : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event")]
        public EntityEvent Event { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"entity")]
        public NEntity Entity { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActionStep : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"condition")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Condition { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"wait")]
        public WaitAction Wait
        {
            get { return __pbn__action.Is(2) ? ((WaitAction)__pbn__action.Object) : default; }
            set { __pbn__action = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializeWait() => __pbn__action.Is(2);
        public void ResetWait() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__action, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__action;

        [global::ProtoBuf.ProtoMember(3, Name = @"move")]
        public MoveAction Move
        {
            get { return __pbn__action.Is(3) ? ((MoveAction)__pbn__action.Object) : default; }
            set { __pbn__action = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeMove() => __pbn__action.Is(3);
        public void ResetMove() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__action, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"interact")]
        public InteractAction Interact
        {
            get { return __pbn__action.Is(4) ? ((InteractAction)__pbn__action.Object) : default; }
            set { __pbn__action = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeInteract() => __pbn__action.Is(4);
        public void ResetInteract() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__action, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"select")]
        public SelectAction Select
        {
            get { return __pbn__action.Is(5) ? ((SelectAction)__pbn__action.Object) : default; }
            set { __pbn__action = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializeSelect() => __pbn__action.Is(5);
        public void ResetSelect() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__action, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"input")]
        public InputAction Input
        {
            get { return __pbn__action.Is(6) ? ((InputAction)__pbn__action.Object) : default; }
            set { __pbn__action = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializeInput() => __pbn__action.Is(6);
        public void ResetInput() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__action, 6);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WaitAction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"allowed_contact_obj_ids", IsPacked = true)]
        public int[] AllowedContactObjIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MoveAction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Direction direction { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"allowed_contact_obj_ids", IsPacked = true)]
        public int[] AllowedContactObjIds { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Direction
        {
            [global::ProtoBuf.ProtoEnum(Name = @"LEFT")]
            Left = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"RIGHT")]
            Right = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InteractAction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SelectAction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"selection")]
        public int Selection { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InputAction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"input_text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string InputText { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public NetMessageRequest Request { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public NetMessageResponse Response { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetMessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public AgentCreateRequest agentCreateRequest { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public AgentLoadRequest agentLoadRequest { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public SceneStartRequest sceneStartRequest { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public SceneStopRequest sceneStopRequest { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public AgentInterruptRequest agentInterruptRequest { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public MemoryBackupRequest memoryBackupRequest { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public MemoryRestoreRequest memoryRestoreRequest { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public MemoryDeleteCurrentRequest memoryDeleteCurrentRequest { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public UserSendMessageRequest userSendMessageRequest { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public UserSendFeedbackRequest userSendFeedbackRequest { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public UserSendMessageAllRequest userSendMessageAllRequest { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public SendToolResultMessageRequest sendToolResultMessageRequest { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public AgentSendMessageRequest agentSendMessageRequest { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public AgentStopActionRequest agentStopActionRequest { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public AgentObserveRequest agentObserveRequest { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public AgentMonitorTargetRequest agentMonitorTargetRequest { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public AgentGetMonitorRecordsRequest agentGetMonitorRecordsRequest { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public AgentMoveRequest agentMoveRequest { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public AgentFollowTargetRequest agentFollowTargetRequest { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public AgentInteractRequest agentInteractRequest { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public AgentSelectRequest agentSelectRequest { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        public AgentInputRequest agentInputRequest { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public AgentPlanActionSequenceRequest agentPlanActionSequenceRequest { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public AgentStartActionSequenceRequest agentStartActionSequenceRequest { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public AgentContinueActionSequenceRequest agentContinueActionSequenceRequest { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        public AgentStopActionSequenceRequest agentStopActionSequenceRequest { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public AgentSetTimerRequest agentSetTimerRequest { get; set; }

        [global::ProtoBuf.ProtoMember(28)]
        public AgentGetTimerListRequest agentGetTimerListRequest { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        public AgentRemoveTimerRequest agentRemoveTimerRequest { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        public AgentGetWorldEventLogRequest agentGetWorldEventLogRequest { get; set; }

        [global::ProtoBuf.ProtoMember(31)]
        public AgentExportSkillsRequest agentExportSkillsRequest { get; set; }

        [global::ProtoBuf.ProtoMember(32)]
        public AgentGetWorldEventSummaryRequest agentGetWorldEventSummaryRequest { get; set; }

        [global::ProtoBuf.ProtoMember(33)]
        public InitRequest initRequest { get; set; }

        [global::ProtoBuf.ProtoMember(34)]
        public CloseRequest closeRequest { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetMessageResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public AgentCreateResponse agentCreateResponse { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public AgentLoadResponse agentLoadResponse { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public SceneStartResponse sceneStartResponse { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public SceneStopResponse sceneStopResponse { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public AgentInterruptResponse agentInterruptResponse { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public MemoryBackupResponse memoryBackupResponse { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public MemoryRestoreResponse memoryRestoreResponse { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public MemoryDeleteCurrentResponse memoryDeleteCurrentResponse { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public AgentExportSkillsResponse agentExportSkillsResponse { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public InitResponse initResponse { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public CloseResponse closeResponse { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentCreateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"desc")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Desc { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentCreateResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentLoadRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentLoadResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"agent_names")]
        public global::System.Collections.Generic.List<string> AgentNames { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneStartRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"map_id")]
        public int MapId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneStartResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneStopRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SceneStopResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentInterruptRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentInterruptResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InitRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InitResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CloseRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CloseResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemoryBackupRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"slot_id")]
        public int SlotId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemoryBackupResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemoryRestoreRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"slot_id")]
        public int SlotId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemoryRestoreResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemoryDeleteCurrentRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemoryDeleteCurrentResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentExportSkillsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentExportSkillsResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"success")]
        public bool Success { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"errormsg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Errormsg { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"skill_count")]
        public int SkillCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserSendMessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"user_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserMessage { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"force_interrupt")]
        public bool ForceInterrupt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserSendFeedbackRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"user_feedback")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserFeedback { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"force_interrupt")]
        public bool ForceInterrupt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserSendMessageAllRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string UserMessage { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"force_interrupt")]
        public bool ForceInterrupt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendToolResultMessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"tool_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ToolName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"result")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Result { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentSendMessageRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"ai_message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string AiMessage { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentStopActionRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"action_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ActionType { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentObserveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentMonitorTargetRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"object_index")]
        public int ObjectIndex { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"object_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ObjectName { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentGetMonitorRecordsRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"monitor_target_index")]
        public int MonitorTargetIndex { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentMoveRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"is_right")]
        public bool IsRight { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"distance")]
        public float Distance { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentFollowTargetRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"object_index")]
        public int ObjectIndex { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"object_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ObjectName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"min_distance")]
        public float MinDistance { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"max_distance")]
        public float MaxDistance { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentInteractRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentSelectRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"selection")]
        public int Selection { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentInputRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"input_text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string InputText { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentPlanActionSequenceRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"action_sequence")]
        public global::System.Collections.Generic.List<ActionStep> ActionSequences { get; } = new global::System.Collections.Generic.List<ActionStep>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentStartActionSequenceRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentContinueActionSequenceRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentStopActionSequenceRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentSetTimerRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"timer_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TimerName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"delay_seconds")]
        public float DelaySeconds { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"timer_description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TimerDescription { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"timer_repeat")]
        public bool TimerRepeat { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentGetTimerListRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentRemoveTimerRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"timer_id")]
        public int TimerId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentGetWorldEventLogRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AgentGetWorldEventSummaryRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"agent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Agent { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RequestId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"max_events")]
        public int MaxEvents { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ignore_self_events")]
        public bool IgnoreSelfEvents { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"RESULT")]
    public enum Result
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS")]
        Success = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FAILED")]
        Failed = 1,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHARACTER_TYPE")]
    public enum CharacterType
    {
        Player = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"NPC")]
        Npc = 1,
        Monster = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHARACTER_CLASS")]
    public enum CharacterClass
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"WARRIOR")]
        Warrior = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WIZARD")]
        Wizard = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ARCHER")]
        Archer = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"CHARACTER_STATE")]
    public enum CharacterState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IDLE")]
        Idle = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"MOVE")]
        Move = 1,
    }

    [global::ProtoBuf.ProtoContract(Name = @"ENTITY_EVENT")]
    public enum EntityEvent
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EVT_NONE")]
        EvtNone = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EVT_IDLE")]
        EvtIdle = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"EVT_MOVE_FWD")]
        EvtMoveFwd = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"EVT_MOVE_BACK")]
        EvtMoveBack = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"EVT_JUMP")]
        EvtJump = 4,
    }

    [global::ProtoBuf.ProtoContract(Name = @"DIRECTION")]
    public enum Direction
    {
        [global::ProtoBuf.ProtoEnum(Name = @"LEFT")]
        Left = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"RIGHT")]
        Right = 1,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
