[project]
name = "PythonServer"
version = "0.1.0"
dependencies = [
    "dotenv>=0.9.9",
    "graphiti>=0.1.13",
    "graphiti-core>=0.19.0",
    "ipython>=8.37.0",
    "kuzu==0.11.2",
    "langchain>=0.3.27",
    "langchain-community>=0.3.29",
    "langchain-openai>=0.3.32",
    "langgraph>=0.6.6",
    "pandas>=2.3.2",
    "pip>=25.3",
    "protobuf==3.20.3",
    "yfiles-jupyter-graphs-for-kuzu>=1.1.1",
]
