syntax = "proto3";

package SkillBridge.Message;

option csharp_namespace = "SkillBridge.Message";
option py_generic_services = false;
option cc_enable_arenas = true;

////////////////////////////////////////////////////////////////
//
//  Basic Defines
//
////////////////////////////////////////////////////////////////
enum RESULT
{
	SUCCESS = 0;
	FAILED = 1;
}

enum CHARACTER_TYPE
{
	Player = 0;
	NPC = 1;
	Monster = 2;
}

enum CHARACTER_CLASS
{
	NONE = 0;
	WARRIOR = 1;
	WIZARD = 2;
	ARCHER = 3;
}

enum CHARACTER_STATE
{
	IDLE = 0;
	MOVE = 1;
}

enum ENTITY_EVENT
{
	NONE = 0;
	IDLE = 1;
	MOVE_FWD = 2;
	MOVE_BACK = 3;
	JUMP = 4;
}

message NUserInfo {
	int32 id = 1;
	NPlayerInfo player = 2;
}

message NPlayerInfo {
	int32 id = 1;
	repeated NCharacterInfo characters = 2;
}

message NCharacterInfo {
	int32 id = 1;
	int32 tid = 2;
	string name = 3;
	CHARACTER_TYPE type = 4;
	CHARACTER_CLASS class = 5;
	int32 level = 6;
	int32 mapId = 7;
	NEntity entity = 8;
}

message NVector3
{
	int32 x = 1;
	int32 y = 2;
	int32 z = 3;
}

////////////////////////////////////////////////////////////////
//
//  Entities
//
////////////////////////////////////////////////////////////////


message NEntity {
	int32 id = 1;
	NVector3 position = 2;
	NVector3 direction = 3;
	int32 speed = 4;
}

message NEntitySync {
	int32 id = 1;
	ENTITY_EVENT event = 2;
	NEntity entity = 3;
	
}

////////////////////////////////////////////////////////////////
//
//  Messages
//
////////////////////////////////////////////////////////////////

message NetMessage{
	NetMessageRequest Request = 1;
	NetMessageResponse Response = 2;
}

message NetMessageRequest{
	AgentCreateRequest agentCreateRequest = 1;
	SceneStartRequest sceneStartRequest = 2;
	UserSendMessageRequest userSendMessageRequest = 3;
	AgentSendMessageRequest agentSendMessageRequest = 4;
}

message NetMessageResponse{
	AgentCreateResponse agentCreateResponse = 1;
	SceneStartResponse sceneStartResponse = 2;
}

// 创建Agent
message AgentCreateRequest {
	string name = 1;
	string desc = 2;
}

message AgentCreateResponse {
	bool success = 1;
	string errormsg = 2;
}

// 开启场景
message SceneStartRequest {
	int32 map_id = 1;
}

message SceneStartResponse {
	bool success = 1;
	string errormsg = 2;
}

// 用户向智能体发消息
message UserSendMessageRequest {
	string agent = 1;
	string user_message = 2;
}

// 智能体向用户发消息
message AgentSendMessageRequest {
	string agent = 1;
	string ai_message = 2;
}
